// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhnmnlvejkckndtdpuyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxobm1ubHZlamtja25kdGRwdXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDQ4OTYsImV4cCI6MjA1ODQyMDg5Nn0.F5JB55UN2UsXwjBZbYaHIT_kseBsIjQCjb9mNnHsOJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});